name: Valter Júnior
description: Reflexões de um desenvolvedor de software
meta_description: "Valter Júnior, reflexões de um desenvolvedor de software"
keywords: "desenvolvimento de software, qualidade de software, agile, testes, engenharia de software"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jvcjunior.github.io'
google_analytics: 'UA-64196808-1'
disqus: jvcjunior

# Details for the RSS feed generator
url:            'jvcjunior.github.io'
author:         'Valter Júnior'
